// GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platform7 = new Entity("Platform")
engine.addEntity(platform7)
const platform7transform = new Transform({
  position: new Vector3(7.5, 2.5, 9.5),
  rotation: new Quaternion(0, 1, 0, -4.371139E-08),
  scale: new Vector3(1, 1, 1)
})
platform7.addComponentOrReplace(platform7transform)
const platform7GLTFShape = new GLTFShape("models/5d6202b7-d5b7-4bc6-a4a2-c1e6b35c0bb6/Raft_01/Raft_01.glb")
platform7GLTFShape.withCollisions = true
platform7GLTFShape.isPointerBlocker = true
platform7GLTFShape.visible = true
platform7.addComponentOrReplace(platform7GLTFShape)

const platform29 = new Entity("Platform2")
engine.addEntity(platform29)
const platform29transform = new Transform({
  position: new Vector3(13.5, 7.5, 2.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
platform29.addComponentOrReplace(platform29transform)
const platform29GLTFShape = new GLTFShape("models/5d6202b7-d5b7-4bc6-a4a2-c1e6b35c0bb6/Raft_01/Raft_01.glb")
platform29GLTFShape.withCollisions = true
platform29GLTFShape.isPointerBlocker = true
platform29GLTFShape.visible = true
platform29.addComponentOrReplace(platform29GLTFShape)

const docksModuleStairs0112 = new Entity("Docks Module Stairs 01")
engine.addEntity(docksModuleStairs0112)
const docksModuleStairs0112transform = new Transform({
  position: new Vector3(2.165799, -0.2861152, 2.999999),
  rotation: new Quaternion(0, -0.7071066, 0, 0.7071071),
  scale: new Vector3(1.75, 1.75, 1.25)
})
docksModuleStairs0112.addComponentOrReplace(docksModuleStairs0112transform)
const docksModuleStairs0112GLTFShape = new GLTFShape("models/fdb0f713-5c34-4f5a-811b-8c4417b5ffd5/DocksModuleStairs_01/DocksModuleStairs_01.glb")
docksModuleStairs0112GLTFShape.withCollisions = true
docksModuleStairs0112GLTFShape.isPointerBlocker = true
docksModuleStairs0112GLTFShape.visible = true
docksModuleStairs0112.addComponentOrReplace(docksModuleStairs0112GLTFShape)

const docksModuleStairs0113 = new Entity("Docks Module Stairs 01")
engine.addEntity(docksModuleStairs0113)
const docksModuleStairs0113transform = new Transform({
  position: new Vector3(4.617132, 1.03581, 2.999997),
  rotation: new Quaternion(0, -0.7071066, 0, 0.7071071),
  scale: new Vector3(1.75, 1.75, 1.25)
})
docksModuleStairs0113.addComponentOrReplace(docksModuleStairs0113transform)
const docksModuleStairs0113GLTFShape = new GLTFShape("models/fdb0f713-5c34-4f5a-811b-8c4417b5ffd5/DocksModuleStairs_01/DocksModuleStairs_01.glb")
docksModuleStairs0113GLTFShape.withCollisions = true
docksModuleStairs0113GLTFShape.isPointerBlocker = true
docksModuleStairs0113GLTFShape.visible = true
docksModuleStairs0113.addComponentOrReplace(docksModuleStairs0113GLTFShape)

const fenceWoodEnd0114 = new Entity("Fence Wood End 01")
engine.addEntity(fenceWoodEnd0114)
const fenceWoodEnd0114transform = new Transform({
  position: new Vector3(6.657, 0, 1.957),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.805, 1.805, 1.805)
})
fenceWoodEnd0114.addComponentOrReplace(fenceWoodEnd0114transform)
const fenceWoodEnd0114GLTFShape = new GLTFShape("models/6d56fcf8-d9e5-4fbb-a13f-8444a36ef7a3/FenceWoodEnd_01/FenceWoodEnd_01.glb")
fenceWoodEnd0114GLTFShape.withCollisions = true
fenceWoodEnd0114GLTFShape.isPointerBlocker = true
fenceWoodEnd0114GLTFShape.visible = true
fenceWoodEnd0114.addComponentOrReplace(fenceWoodEnd0114GLTFShape)

const fenceWoodEnd0115 = new Entity("Fence Wood End 01")
engine.addEntity(fenceWoodEnd0115)
const fenceWoodEnd0115transform = new Transform({
  position: new Vector3(6.694326, 0, 4.094232),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.805235, 1.805235, 1.805235)
})
fenceWoodEnd0115.addComponentOrReplace(fenceWoodEnd0115transform)
const fenceWoodEnd0115GLTFShape = new GLTFShape("models/6d56fcf8-d9e5-4fbb-a13f-8444a36ef7a3/FenceWoodEnd_01/FenceWoodEnd_01.glb")
fenceWoodEnd0115GLTFShape.withCollisions = true
fenceWoodEnd0115GLTFShape.isPointerBlocker = true
fenceWoodEnd0115GLTFShape.visible = true
fenceWoodEnd0115.addComponentOrReplace(fenceWoodEnd0115GLTFShape)

const tent0216 = new Entity("Tent 02")
engine.addEntity(tent0216)
const tent0216transform = new Transform({
  position: new Vector3(13.33273, 0, 3.144863),
  rotation: new Quaternion(0, 0.7933531, 0, 0.6087617),
  scale: new Vector3(1.102134, 1.102134, 1.102134)
})
tent0216.addComponentOrReplace(tent0216transform)
const tent0216GLTFShape = new GLTFShape("models/0149cae5-9e33-48aa-a346-94f02091ec75/Tent_02/Tent_02.glb")
tent0216GLTFShape.withCollisions = true
tent0216GLTFShape.isPointerBlocker = true
tent0216GLTFShape.visible = true
tent0216.addComponentOrReplace(tent0216GLTFShape)

const tent0217 = new Entity("Tent 02")
engine.addEntity(tent0217)
const tent0217transform = new Transform({
  position: new Vector3(13.61891, 0, 9.603185),
  rotation: new Quaternion(0, 0.5849327, 0, 0.8110819),
  scale: new Vector3(1.102134, 1.102134, 1.102134)
})
tent0217.addComponentOrReplace(tent0217transform)
const tent0217GLTFShape = new GLTFShape("models/0149cae5-9e33-48aa-a346-94f02091ec75/Tent_02/Tent_02.glb")
tent0217GLTFShape.withCollisions = true
tent0217GLTFShape.isPointerBlocker = true
tent0217GLTFShape.visible = true
tent0217.addComponentOrReplace(tent0217GLTFShape)

const floorBaseGrass0118 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0118)
const floorBaseGrass0118transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0118.addComponentOrReplace(floorBaseGrass0118transform)
const floorBaseGrass0118GLTFShape = new GLTFShape("models/c9b17021-765c-4d9a-9966-ce93a9c323d1/FloorBaseGrass_01/FloorBaseGrass_01.glb")
floorBaseGrass0118GLTFShape.withCollisions = true
floorBaseGrass0118GLTFShape.isPointerBlocker = true
floorBaseGrass0118GLTFShape.visible = true
floorBaseGrass0118.addComponentOrReplace(floorBaseGrass0118GLTFShape)

const fenceStoneTallSmall0119 = new Entity("Fence Stone Tall Small 01")
engine.addEntity(fenceStoneTallSmall0119)
const fenceStoneTallSmall0119transform = new Transform({
  position: new Vector3(1.353, 0, 5.946),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(6, 6, 7.97)
})
fenceStoneTallSmall0119.addComponentOrReplace(fenceStoneTallSmall0119transform)
const fenceStoneTallSmall0119GLTFShape = new GLTFShape("models/43888045-631f-4907-9bf5-e0529d9cc10d/FenceStoneTallSmall_01/FenceStoneTallSmall_01.glb")
fenceStoneTallSmall0119GLTFShape.withCollisions = true
fenceStoneTallSmall0119GLTFShape.isPointerBlocker = true
fenceStoneTallSmall0119GLTFShape.visible = true
fenceStoneTallSmall0119.addComponentOrReplace(fenceStoneTallSmall0119GLTFShape)

const fenceWoodLarge0120 = new Entity("Fence Wood Large 01")
engine.addEntity(fenceWoodLarge0120)
const fenceWoodLarge0120transform = new Transform({
  position: new Vector3(11.17, 7.56, 11.32),
  rotation: new Quaternion(0.2705981, 0.2705981, -0.6532815, -0.6532815),
  scale: new Vector3(1, 1, 1)
})
fenceWoodLarge0120.addComponentOrReplace(fenceWoodLarge0120transform)
const fenceWoodLarge0120GLTFShape = new GLTFShape("models/8f2069c1-ab16-4b16-b2cb-f2cc9238917e/FenceWoodLarge_01/FenceWoodLarge_01.glb")
fenceWoodLarge0120GLTFShape.withCollisions = true
fenceWoodLarge0120GLTFShape.isPointerBlocker = true
fenceWoodLarge0120GLTFShape.visible = true
fenceWoodLarge0120.addComponentOrReplace(fenceWoodLarge0120GLTFShape)

const log0121 = new Entity("Log 01")
engine.addEntity(log0121)
const log0121transform = new Transform({
  position: new Vector3(12.09016, 6.806, 9.224561),
  rotation: new Quaternion(-0.270598, 0.6532815, -0.6532815, -0.270598),
  scale: new Vector3(0.727, 0.727, 0.571)
})
log0121.addComponentOrReplace(log0121transform)
const log0121GLTFShape = new GLTFShape("models/26d204c5-52df-475c-a6b2-999ce1b716bd/Log_01/Log_01.glb")
log0121GLTFShape.withCollisions = true
log0121GLTFShape.isPointerBlocker = true
log0121GLTFShape.visible = true
log0121.addComponentOrReplace(log0121GLTFShape)

const log0122 = new Entity("Log 01")
engine.addEntity(log0122)
const log0122transform = new Transform({
  position: new Vector3(10.63316, 5.988, 7.764561),
  rotation: new Quaternion(-0.3794095, -0.1205906, -0.9159756, 0.04995031),
  scale: new Vector3(1, 1, 1.656)
})
log0122.addComponentOrReplace(log0122transform)
const log0122GLTFShape = new GLTFShape("models/26d204c5-52df-475c-a6b2-999ce1b716bd/Log_01/Log_01.glb")
log0122GLTFShape.withCollisions = true
log0122GLTFShape.isPointerBlocker = true
log0122GLTFShape.visible = true
log0122.addComponentOrReplace(log0122GLTFShape)

const fenceWoodEnd0123 = new Entity("Fence Wood End 01")
engine.addEntity(fenceWoodEnd0123)
const fenceWoodEnd0123transform = new Transform({
  position: new Vector3(9.286, 2.37, 6.381),
  rotation: new Quaternion(0.2391176, 0.3696438, -0.09904577, 0.8923991),
  scale: new Vector3(1.805, 3.055, 1.805)
})
fenceWoodEnd0123.addComponentOrReplace(fenceWoodEnd0123transform)
const fenceWoodEnd0123GLTFShape = new GLTFShape("models/6d56fcf8-d9e5-4fbb-a13f-8444a36ef7a3/FenceWoodEnd_01/FenceWoodEnd_01.glb")
fenceWoodEnd0123GLTFShape.withCollisions = true
fenceWoodEnd0123GLTFShape.isPointerBlocker = true
fenceWoodEnd0123GLTFShape.visible = true
fenceWoodEnd0123.addComponentOrReplace(fenceWoodEnd0123GLTFShape)

const fenceWoodEnd0124 = new Entity("Fence Wood End 01")
engine.addEntity(fenceWoodEnd0124)
const fenceWoodEnd0124transform = new Transform({
  position: new Vector3(3.166, 2.759, 5.445),
  rotation: new Quaternion(-1.131334E-08, 0.9659259, -0.2588191, -4.222196E-08),
  scale: new Vector3(1.805, 3.055, 1.805)
})
fenceWoodEnd0124.addComponentOrReplace(fenceWoodEnd0124transform)
const fenceWoodEnd0124GLTFShape = new GLTFShape("models/6d56fcf8-d9e5-4fbb-a13f-8444a36ef7a3/FenceWoodEnd_01/FenceWoodEnd_01.glb")
fenceWoodEnd0124GLTFShape.withCollisions = true
fenceWoodEnd0124GLTFShape.isPointerBlocker = true
fenceWoodEnd0124GLTFShape.visible = true
fenceWoodEnd0124.addComponentOrReplace(fenceWoodEnd0124GLTFShape)

const log0125 = new Entity("Log 01")
engine.addEntity(log0125)
const log0125transform = new Transform({
  position: new Vector3(3.186202, 6.377253, 3.513726),
  rotation: new Quaternion(0.9914448, 3.352762E-08, 2.82857E-07, -0.1305264),
  scale: new Vector3(1, 1, 1.656)
})
log0125.addComponentOrReplace(log0125transform)
const log0125GLTFShape = new GLTFShape("models/26d204c5-52df-475c-a6b2-999ce1b716bd/Log_01/Log_01.glb")
log0125GLTFShape.withCollisions = true
log0125GLTFShape.isPointerBlocker = true
log0125GLTFShape.visible = true
log0125.addComponentOrReplace(log0125GLTFShape)

const log0126 = new Entity("Log 01")
engine.addEntity(log0126)
const log0126transform = new Transform({
  position: new Vector3(3.188535, 7.195, 1.451),
  rotation: new Quaternion(0.7071068, 0, 0, 0.7071068),
  scale: new Vector3(0.727, 0.727, 0.571)
})
log0126.addComponentOrReplace(log0126transform)
const log0126GLTFShape = new GLTFShape("models/26d204c5-52df-475c-a6b2-999ce1b716bd/Log_01/Log_01.glb")
log0126GLTFShape.withCollisions = true
log0126GLTFShape.isPointerBlocker = true
log0126GLTFShape.visible = true
log0126.addComponentOrReplace(log0126GLTFShape)

const fenceWoodLarge0127 = new Entity("Fence Wood Large 01")
engine.addEntity(fenceWoodLarge0127)
const fenceWoodLarge0127transform = new Transform({
  position: new Vector3(4.899, 7.949, 5.575),
  rotation: new Quaternion(0, 0, 0.7071068, 0.7071068),
  scale: new Vector3(1, 1.71, 1)
})
fenceWoodLarge0127.addComponentOrReplace(fenceWoodLarge0127transform)
const fenceWoodLarge0127GLTFShape = new GLTFShape("models/8f2069c1-ab16-4b16-b2cb-f2cc9238917e/FenceWoodLarge_01/FenceWoodLarge_01.glb")
fenceWoodLarge0127GLTFShape.withCollisions = true
fenceWoodLarge0127GLTFShape.isPointerBlocker = true
fenceWoodLarge0127GLTFShape.visible = true
fenceWoodLarge0127.addComponentOrReplace(fenceWoodLarge0127GLTFShape)

const cannon0128 = new Entity("Cannon 01")
engine.addEntity(cannon0128)
const cannon0128transform = new Transform({
  position: new Vector3(2.6, 7.986, 4.109),
  rotation: new Quaternion(0, 0.9238796, 0, -0.3826834),
  scale: new Vector3(1, 1, 1)
})
cannon0128.addComponentOrReplace(cannon0128transform)
const cannon0128GLTFShape = new GLTFShape("models/f25b55b3-3260-4d81-b8e5-a2654ac9a3f5/Cannon_01/Cannon_01.glb")
cannon0128GLTFShape.withCollisions = true
cannon0128GLTFShape.isPointerBlocker = true
cannon0128GLTFShape.visible = true
cannon0128.addComponentOrReplace(cannon0128GLTFShape)

const cannonball0329 = new Entity("Cannonball 03")
engine.addEntity(cannonball0329)
const cannonball0329transform = new Transform({
  position: new Vector3(4.133, 8.25, 4.143),
  rotation: new Quaternion(0, 0.5187733, 0, 0.8549119),
  scale: new Vector3(1, 1, 1)
})
cannonball0329.addComponentOrReplace(cannonball0329transform)
const cannonball0329GLTFShape = new GLTFShape("models/8d0f5de1-c3ef-4752-b60f-f755cd3ecf27/Cannonball_03/Cannonball_03.glb")
cannonball0329GLTFShape.withCollisions = true
cannonball0329GLTFShape.isPointerBlocker = true
cannonball0329GLTFShape.visible = true
cannonball0329.addComponentOrReplace(cannonball0329GLTFShape)

export let scene = {
  platform:{
    entity: platform7,
    transform: platform7transform,
    GLTFShape: platform7GLTFShape,
  },
  platform2:{
    entity: platform29,
    transform: platform29transform,
    GLTFShape: platform29GLTFShape,
  },
}

